name: E-commerce
repository: https://github.com/kietpham-agilityio/e-commerce

packages:
  - .
  - e_commerce_app
  - packages/*
  - packages/*/*
  - packages/*/*/*

scripts:
  postbootstrap: >
    melos exec -- puro flutter pub get

  postclean: >
    melos exec -- puro flutter clean

  build_runner:
    run: |
      melos exec -- "puro flutter pub run build_runner build --delete-conflicting-outputs"
    packageFilters:
      scope:
        - ec_core
        - e_commerce_app
        - ec_themes

  generate_l10n:
    run: |
      melos exec -- "puro flutter gen-l10n"
    packageFilters:
      scope:
        - ec_l10n

  custom_lint_app:
    run: |
      melos exec -- "dart run custom_lint"
    packageFilters:
      scope:
        - e_commerce_app
