name: E-commerce
repository: https://github.com/kietpham-agilityio/e-commerce

packages:
  - .
  - e_commerce_app
  - packages/*
  - packages/*/*
  - packages/*/*/*

scripts:
  postbootstrap: >
    melos exec -- puro flutter pub get && 
    melos run build_runner

  build_runner:
    run: |
      melos exec -- "puro flutter pub run build_runner build --delete-conflicting-outputs"
    packageFilters:
      scope:
        - e_commerce

  custom_lint_app:
    run: |
      melos exec -- "dart run custom_lint"
    packageFilters:
      scope:
        - e_commerce_app

