name: ec_core
description: "Core packages for E-Commerce application"
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ^3.7.2
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

    # Simplify to create model
  freezed: ^2.5.2

  # Annotations for the freezed code-generator.
  freezed_annotation: ^2.4.1

  # Equatable is a package that helps to implement value-based equality without needing to override `==` and `hashCode`.
  equatable: ^2.0.5

  # Http client library
  dio: ^5.5.0+1

  # Functional programming
  fpdart: ^1.1.0

  retrofit: ^4.3.0

  json_annotation: ^4.9.0

  # Logger for dio
  pretty_dio_logger: ^1.4.0

  talker_flutter: ^5.0.0

  talker_dio_logger: ^5.0.0

  get_it: ^7.6.4

  # State management
  flutter_bloc: ^9.1.1

  # Local database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # For dummy data
  faker: ^2.1.0

  # Mock library
  mocktail: ^1.0.4

  # Mock library
  http_mock_adapter: ^0.6.1

  build_runner: ^2.4.11

  retrofit_generator: ">=8.0.0 <10.0.0"
  json_serializable: ^6.8.0
  isar_generator: ^3.1.0+1

  bloc_test: ^10.0.0

dependency_overrides:
  analyzer: ^6.0.0
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
