name: ec_core
description: "Core packages for E-Commerce application"
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ^3.7.2
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

    # Simplify to create model
  freezed: ^2.5.2

  # Annotations for the freezed code-generator.
  freezed_annotation: ^2.4.1

  # Equatable is a package that helps to implement value-based equality without needing to override `==` and `hashCode`.
  equatable: ^2.0.5

  # Http client library
  dio: ^5.5.0+1

  # Functional programming
  fpdart: ^1.1.0

  retrofit: ^4.3.0

  json_annotation: ^4.9.0

  # Logger for dio
  pretty_dio_logger: ^1.4.0

  talker_flutter: ^5.0.0

  talker_dio_logger: ^5.0.0

  get_it: ^8.2.0

  isar: ^3.1.0+1

  isar_flutter_libs:
    git:
      url: https://github.com/MrLittleWhite/isar_flutter_libs.git

  path_provider: ^2.1.4
  shared_preferences: ^2.3.2

  flutter_bloc: ^9.1.1

  simple_speed_dial: ^0.1.7

  flutter_dotenv: ^6.0.0
  # A complete solution to create Local and Push Notifications, customizing buttons, images, sounds, emoticons and applying many different layouts for Flutter apps.
  awesome_notifications: ^0.10.1

  # Awesome Notifications add-on plugin to send push notifications through Firebase Cloud Messaging, enabling all awesome notifications features.
  awesome_notifications_fcm: ^0.10.1

  # Permission plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API to request and check permissions.
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # For dummy data
  faker: ^2.1.0

  # Mock library
  mocktail: ^1.0.4

  # Mock library
  http_mock_adapter: ^0.6.1

  build_runner: ^2.4.11

  retrofit_generator: ">=8.0.0 <10.0.0"
  json_serializable: ^6.8.0
  isar_generator: ^3.1.0+1

  bloc_test: ^10.0.0

dependency_overrides:
  analyzer: ^6.0.0
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
