name: ec_core
description: "Core packages for E-Commerce application"
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ^3.7.2
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
