name: ec_core
description: "Core packages for E-Commerce application"
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ^3.7.2
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

    # Simplify to create model
  freezed: ^3.1.0

  # Annotations for the freezed code-generator.
  freezed_annotation: ^3.1.0

  # Equatable is a package that helps to implement value-based equality without needing to override `==` and `hashCode`.
  equatable: ^2.0.5

  # Http client library
  dio: ^5.5.0+1

  # Functional programming
  fpdart: ^1.1.0

  retrofit: ^4.3.0

  json_annotation: ^4.9.0

  # Logger for dio
  pretty_dio_logger: ^1.4.0

  talker_flutter: ^5.0.0

  talker_dio_logger: ^5.0.0

  get_it: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # For dummy data
  faker: ^2.1.0

  # Mock library
  mocktail: ^1.0.4

  # Mock library
  http_mock_adapter: ^0.6.1

  build_runner: ^2.4.11

  retrofit_generator: ">=8.0.0 <10.0.0"
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
