name: ec_l10n
description: Localization package for E-commerce app using flutter_localization
version: 1.0.0
homepage: https://github.com/your-org/e-commerce

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.20.0

flutter:
  uses-material-design: true
  generate: true
